name: Build APK
on:
  push:
    branches: [ "develop" ]

jobs:
  Build-Environment:
    runs-on: "ubuntu-latest"
    
    steps:
    
      - name: "Checkout Code"
        uses: actions/checkout@v3
        
        
      - name: "Check java"
        run: |
          java -version
          
          
      - name: "Run Test"
        run: |
          chmod a+x gradlew
          ./gradlew test
          
      - name: "Run Build"
        run: |
          ./gradlew build
          
      - name: "List  tasks"
        run: |
          ./gradlew tasks