name: Build APK
on:
  push:
    branches: [ "develop" ]

job:
  Build-Environment:
    runs-on: "ubuntu-latest"
    
    steps:
    
      - name: "Checkout Code"
        uses: actions/checkout@v3
      - name: "Check java"
        run: |
          java -version