name: Build APK
on:
  push:
    branches: [ "develop" ]

jobs:
  Build-and-Push:
    runs-on: "ubuntu-latest"
    if: "contains(github.event.head_commit.message, 'build')"
    
    steps:
    
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Check java"
        run: |
          java -version
                   
      - name: "Run Test"
        run: |
          chmod a+x gradlew
          ./gradlew build
          ./gradlew assembleRelease
          # ./gradlew assembleDebug
          ./gradlew app:bundleRelease
      - name: "find Build APK"
        run: |
          find . -iname *.apk -type f 

      # - name: "upload artefact to App Center"
      #   uses: wzieba/AppCenter-Github-Action@v1
      #   with:
      #     appName: "srinivasan-vthink.co.in/test"
      #     token: ${{secrets.APP_CENTER_TOKEN}}
      #     file: ./app/build/outputs/apk/release/app-release-unsigned.apk
      #     group: "tester" 
      #     notifyTesters: "true"

      # - name: "Run Build"
      #   run: |
      #     chmod a+x gradlew
      #     ./gradlew build
          
      # - name: "Build a debug APK"
      #   run: |
      #     ./gradlew assembleDebug
          
