name: Build APK
on:
  push:
    branches: [ "develop" ]

jobs:
  Build-Environment:
    runs-on: "ubuntu-latest"
    
    steps:
    
      - name: "Checkout Code"
        uses: actions/checkout@v3
        
        
#      - name: "Check java"
#        run: |
#          java -version
          
          
#      - name: "Run Test"
#       run: |
#          chmod a+x gradlew
#          ./gradlew test
          
      - name: "Run Build"
        run: |
          chmod a+x gradlew
          ./gradlew build
          
      - name: "Build a debug APK"
        run: |
          ./gradlew assembleDebug

      - name: "verify the build"
        run: |
          find . -type f -iname *.apk
          
      - name: "upload artefact to App Center"
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: "srinivasan-vthink.co.in/test"
          token: ${{secrets.APP_CENTER_TOKEN}}
          file: ./app/build/outputs/apk/release/app-release-unsigned.apk
          group: "test"
          